# Copyright Â© 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: sas-risk-cirrus-mrm-parameters
behavior: merge
literals:
  - SAS_LOG_LEVEL_RISKCIRRUSDEPLOYER=INFO
  - SAS_RISK_CIRRUS_DEPLOYER_INCLUDE_SAMPLES=Y
  - SAS_RISK_CIRRUS_DEPLOYER_RUN_SPECIFIC_INSTALL_STEPS=
  - SAS_RISK_CIRRUS_DEPLOYER_SKIP_SPECIFIC_INSTALL_STEPS=
